In [51]:
import numpy as np

import numpy as np
np.set_printoptions(precision=15)
x = np.array(1/60, dtype=np.float32)


def binary_friendly(x):
    y_f16 = np.array(x, dtype=np.float16)
    y_f64 = np.array(x, dtype=np.float64)
    t = y_f64 - y_f16
    assert t.dtype == np.float64
    print(t, t.dtype, t==0)
    return (t==0)
binary_friendly(15/(1/1 * 25.6))


0.0 float64 True


True

In [55]:
import numpy as np

import numpy as np
np.set_printoptions(precision=20)
x = np.array(1/60, dtype=np.float32)
print(x)


0.016666668


In [21]:
floor(StepGameTime/TimeDilation*FrameRate)*TimeDilation/FrameRate

0.03333333333333333

In [26]:
import torch
from torch.distributions.categorical import Categorical
from torch.nn.functional import kl_div
import torch.nn.functional as F

probs = torch.Tensor(
    [0.4, 0.6])
probs2 = torch.Tensor(
    [0.3, 0.7])

print(kl_div(probs.log(), probs2, reduction='sum'))
print(kl_div(probs2.log(), probs, reduction='sum'))
# print(kl_div(probs2.log(), probs, reduction='sum'))


tensor(0.0216)
tensor(0.0226)


client.send_targeted_dgram('ddd')

In [115]:
import torch.nn.functional as F
x = torch.Tensor(
    [0.4, 0.6])
y = torch.Tensor(
    [0.9, 0.1])
kl = F.kl_div(x.log(), y, reduction='sum')
kl  # kl 散度越大，说明概率分布的差异越大

tensor(0.5507)

In [19]:
x.softmax(dim=-1).log()

tensor([-0.7981, -0.5981])

In [54]:
import torch
from torch.distributions.categorical import Categorical
from torch.nn.functional import kl_div
import torch.nn.functional as F
from UTILS.tensor_ops import repeat_at
probs = torch.Tensor(
    [
        [0.4, 0.6],
        [0.3, 0.7],
        [0.3, 0.7]
    ]
    )


# probs.S # (?, n_agent, n_action)
n_agent = probs.shape[-2]
probs_rep = repeat_at(tensor=probs, insert_dim=-2, n_times=n_agent)
# probs_rep.S # (?, n_agent, n_agent, n_action)
probs_rep_transpose = probs_rep.swapaxes(-2,-3)
mat = (probs_rep*probs_rep.log()-probs_rep*probs_rep_transpose.log()).sum(-1)
mat # (?, n_agent, n_agent)
# F.kl_div(probs_rep.log(), probs_rep_transpose, reduction='batchmean')



tensor([[0.0000, 0.0226, 0.0226],
        [0.0216, 0.0000, 0.0000],
        [0.0216, 0.0000, 0.0000]])

In [110]:
# n_agent = 16
tree = get_division_tree(18)
# current_level = 3
# blood_distance = np.ones(shape=(n_agent,n_agent), dtype=np.float64) * np.nan
# for i in range(n_agent):
#     for j in range(n_agent):
#         if i==j:blood_distance[i,j] = 0
#         if not np.isnan(blood_distance[i,j]):
#             continue
#         for t in range(current_level+1):
#             investigate_level = (current_level) - t
#             if tree[investigate_level, i] == tree[investigate_level, j]:
#                 blood_distance[i,j] = t
#                 blood_distance[j,i] = t
#                 break


blood_distance = get_blood_distance(tree, 2)
print(blood_distance)
print(tree)

[[0. 2. 1. 1. 2. 1. 1. 2. 2. 2. 0. 2. 1. 0. 2. 0. 2. 2.]
 [2. 0. 2. 2. 1. 2. 2. 0. 0. 1. 2. 1. 2. 2. 0. 2. 1. 1.]
 [1. 2. 0. 0. 2. 0. 0. 2. 2. 2. 1. 2. 0. 1. 2. 1. 2. 2.]
 [1. 2. 0. 0. 2. 0. 0. 2. 2. 2. 1. 2. 0. 1. 2. 1. 2. 2.]
 [2. 1. 2. 2. 0. 2. 2. 1. 1. 0. 2. 0. 2. 2. 1. 2. 0. 0.]
 [1. 2. 0. 0. 2. 0. 0. 2. 2. 2. 1. 2. 0. 1. 2. 1. 2. 2.]
 [1. 2. 0. 0. 2. 0. 0. 2. 2. 2. 1. 2. 0. 1. 2. 1. 2. 2.]
 [2. 0. 2. 2. 1. 2. 2. 0. 0. 1. 2. 1. 2. 2. 0. 2. 1. 1.]
 [2. 0. 2. 2. 1. 2. 2. 0. 0. 1. 2. 1. 2. 2. 0. 2. 1. 1.]
 [2. 1. 2. 2. 0. 2. 2. 1. 1. 0. 2. 0. 2. 2. 1. 2. 0. 0.]
 [0. 2. 1. 1. 2. 1. 1. 2. 2. 2. 0. 2. 1. 0. 2. 0. 2. 2.]
 [2. 1. 2. 2. 0. 2. 2. 1. 1. 0. 2. 0. 2. 2. 1. 2. 0. 0.]
 [1. 2. 0. 0. 2. 0. 0. 2. 2. 2. 1. 2. 0. 1. 2. 1. 2. 2.]
 [0. 2. 1. 1. 2. 1. 1. 2. 2. 2. 0. 2. 1. 0. 2. 0. 2. 2.]
 [2. 0. 2. 2. 1. 2. 2. 0. 0. 1. 2. 1. 2. 2. 0. 2. 1. 1.]
 [0. 2. 1. 1. 2. 1. 1. 2. 2. 2. 0. 2. 1. 0. 2. 0. 2. 2.]
 [2. 1. 2. 2. 0. 2. 2. 1. 1. 0. 2. 0. 2. 2. 1. 2. 0. 0.]
 [2. 1. 2. 2. 0. 2. 2. 1. 1. 0.

In [72]:

[[ 0.  2.  2. nan  2. nan  2. nan nan  2. nan  2. nan nan  2. nan]
 [ 2.  0.  2. nan  2. nan  2. nan nan  2. nan  2. nan nan  2. nan]
 [ 2.  2.  0. nan  2. nan  2. nan nan  2. nan  2. nan nan  2. nan]
 [nan nan nan  0. nan  2. nan  2.  2. nan  2. nan  2.  2. nan  2.]
 [ 2.  2.  2. nan  0. nan  2. nan nan  2. nan  2. nan nan  2. nan]
 [nan nan nan  2. nan  0. nan  2.  2. nan  2. nan  2.  2. nan  2.]
 [ 2.  2.  2. nan  2. nan  0. nan nan  2. nan  2. nan nan  2. nan]
 [nan nan nan  2. nan  2. nan  0.  2. nan  2. nan  2.  2. nan  2.]
 [nan nan nan  2. nan  2. nan  2.  0. nan  2. nan  2.  2. nan  2.]
 [ 2.  2.  2. nan  2. nan  2. nan nan  0. nan  2. nan nan  2. nan]
 [nan nan nan  2. nan  2. nan  2.  2. nan  0. nan  2.  2. nan  2.]
 [ 2.  2.  2. nan  2. nan  2. nan nan  2. nan  0. nan nan  2. nan]
 [nan nan nan  2. nan  2. nan  2.  2. nan  2. nan  0.  2. nan  2.]
 [nan nan nan  2. nan  2. nan  2.  2. nan  2. nan  2.  0. nan  2.]
 [ 2.  2.  2. nan  2. nan  2. nan nan  2. nan  2. nan nan  0. nan]
 [nan nan nan  2. nan  2. nan  2.  2. nan  2. nan  2.  2. nan  0.]]

 

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  1,  0,  1,  1,  1,  1,  0,  1,  0,  0,  0,  1,  0,  0],
       [ 1,  0,  3,  2,  3,  1,  1,  1,  2,  3,  0,  2,  2,  3,  0,  0],
       [ 1,  0,  3,  5,  7,  6,  1,  6,  2,  7,  4,  5,  2,  3,  4,  0],
       [12,  0,  3, 11, 15,  6,  1, 13, 10,  7,  9,  5,  2, 14,  4,  8]])

In [2]:
import pickle
with open('RECYCLE/wifi', 'rb') as f:
    p_list = pickle.load(f)

p_list

{'d1': tensor([1.1618e-13, 4.3868e-16, 3.4678e-18, 0.0000e+00, 1.0000e+00, 8.3701e-14,
         1.8273e-12], device='cuda:0', requires_grad=True),
 'd2': tensor([0.0756, 0.2109, 0.0628, 0.0104, 0.3506, 0.1273, 0.1624],
        device='cuda:0', requires_grad=True)}

In [32]:
import torch
import torch.nn.functional as F
from torch.distributions.categorical import Categorical
from torch.nn.functional import kl_div


logits1 = torch.Tensor([  4.4786,  -1.1005,  -5.9407, -15.7646,  5.2623,   4.1508,   7.2341]).type(torch.DoubleTensor)
logits2 = torch.Tensor([ -0.5480,  0.4779, -0.7330, -2.5290,  0.9862, -0.0273,  0.2163]).type(torch.DoubleTensor)

dist1 = Categorical(logits = logits1)
dist2 = Categorical(logits = logits2)
print(dist1.probs)
print(dist2.probs)
from torch.distributions import kl_divergence

print(kl_divergence(dist1, dist2))
print(kl_divergence(dist2, dist1))


tensor([5.0909e-02, 1.9223e-04, 1.5197e-06, 8.2279e-11, 1.1147e-01, 3.6681e-02,
        8.0075e-01], dtype=torch.float64)
tensor([0.0756, 0.2109, 0.0628, 0.0104, 0.3506, 0.1273, 0.1624],
       dtype=torch.float64)
tensor(1.0829, dtype=torch.float64)
tensor(2.6698, dtype=torch.float64)


In [7]:
# probs = torch.Tensor(
#     [0, 1])
# probs2 = torch.Tensor(
#     [0.3, 0.7])

# probs = p_list['d1']
# probs2 = p_list['d2']

# print(kl_div(probs.log(), probs2))
# print(kl_div(probs2.log(), probs))

# probs = torch.Tensor(
#     [0, 1])
# probs2 = torch.Tensor(
#     [0.3, 0.7])

# probs = p_list['d1']
# probs2 = p_list['d2']

# print(kl_div(probs.log(), probs2))
# print(kl_div(probs2.log(), probs))

# probs = torch.Tensor(
#     [0, 1])
# probs2 = torch.Tensor(
#     [0.3, 0.7])

# probs = p_list['d1']
# probs2 = p_list['d2']

# print(kl_div(probs.log(), probs2))
# print(kl_div(probs2.log(), probs))

# probs = torch.Tensor(
#     [0, 1])
# probs2 = torch.Tensor(
#     [0.3, 0.7])

# probs = p_list['d1']
# probs2 = p_list['d2']

# print(kl_div(probs.log(), probs2))
# print(kl_div(probs2.log(), probs))

tensor([1.1618e-13, 4.3868e-16, 3.4678e-18, 0.0000e+00, 1.0000e+00, 8.3701e-14,
        1.8273e-12], device='cuda:0', requires_grad=True)

In [64]:
import torch
import numpy as np
from UTILS.tensor_ops import gather_righthand, repeat_at
def scatter_righthand(scatter_into, src, index, check=True):
    index = index.long()
    i_dim = index.dim()
    s_dim = src.dim()
    t_dim = i_dim - 1
    index_new_shape = list(src.shape)
    index_new_shape[t_dim] = index.shape[t_dim]
    for _ in range(i_dim, s_dim):
        index = index.unsqueeze(-1)
    index_expand = index.expand(index_new_shape)  # only this two line matters
    return scatter_into.scatter(t_dim, index_expand, src)

orig = torch.Tensor([[[ 0,  1,  2], [ 3,  4,  5]],
                    [[ 6,  7,  8], [ 9, 10, 11]],
                    [[12, 13, 14], [15, 16, 17]]])
index = torch.Tensor([[0], [1], [0]])
print(orig)

res      = gather_righthand(src=orig, index=index)
res[:] = 0

orig_fix = orig.clone().detach()
orig_fix = scatter_righthand(orig_fix, src=res, index=index)
print(orig_fix)


# orig.scatter(dim=1,index=index.long(),src=res)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]],

        [[12., 13., 14.],
         [15., 16., 17.]]])
tensor([[[ 0.,  0.,  0.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [15., 16., 17.]]])


In [71]:
index = torch.randint(high=16,size=(64,5))
print('s1')
res = gather_righthand(src,index)
print('s1')
res[:] = 0
print('s2')
resX = scatter_righthand(scatter_into=src, src=res, index=index)
print('s2')
print(resX.S)


s1
s1
s2
s2
torch.Size([64, 16, 8, 88, 888])


In [3]:
import torch
import numpy as np
from UTILS.tensor_ops import gather_righthand, repeat_at
from UTILS.tensor_ops import add_onehot_id_at_last_dim, repeat_at, _2tensor, gather_righthand, scatter_righthand
x_in = torch.Tensor([
    [1,1,1],
    [2,2,2],
    [3,3,3],
    [4,4,4],
])
n_agent = 4


nets = [
    lambda x: x+100,
    lambda x: x+200,
    lambda x: x+300,
    lambda x: x+400
]


x0 = add_onehot_id_at_last_dim(x_in)
# x1 = self.shared_net(x0)
res = []
for i in range(n_agent):
    res.append(nets[i](x0[..., i, :]))
x2 = torch.stack(res, -2)
# x22 = self.nets[0](x1)
print('x2',x2)

######### forward twice: shuffle forward
perm_index = torch.randperm(n_agent, device=x_in.device)   # shape = (n_agent)
print('perm_index',perm_index)

perm_index = perm_index.expand(x_in.shape[:-1]) # shape = (...?, n_agent)
# x_in shape = (...?, n_agent, coredim)
perm_x_in = gather_righthand(src=x_in, index=perm_index, check=False)
perm_x0 = add_onehot_id_at_last_dim(perm_x_in)
perm_res = []
for i in range(n_agent):
    perm_res.append(nets[i](perm_x0[..., i, :]))
perm_x2 = torch.stack(perm_res, -2)

# 103
# 202
# 304
# 401


# 401 vs 101
# 202 vs 202
# 103 vs 303
# 304 vs 404

confact_x2 = torch.zeros_like(perm_x2) + np.nan
confact_x2 = scatter_righthand(scatter_into=confact_x2, src=perm_x2, index=perm_index)
print('confact_x2',confact_x2)

x2 tensor([[101., 101., 101., 101., 100., 100., 100.],
        [202., 202., 202., 200., 201., 200., 200.],
        [303., 303., 303., 300., 300., 301., 300.],
        [404., 404., 404., 400., 400., 400., 401.]])
perm_index tensor([2, 1, 3, 0])
confact_x2 tensor([[401., 401., 401., 400., 400., 400., 401.],
        [202., 202., 202., 200., 201., 200., 200.],
        [103., 103., 103., 101., 100., 100., 100.],
        [304., 304., 304., 300., 300., 301., 300.]])


In [4]:
import torch

res=torch.isnan(torch.tensor([1, float('inf'), 2, float('-inf'), float('nan')]))
print(res)

res=torch.isfinite(torch.tensor([1, float('inf'), 2, float('-inf'), float('nan')]))
print(res)







tensor([False, False, False, False,  True])
tensor([ True, False,  True, False, False])
